with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
filename: "mock_{{.InterfaceName}}.go"
packages:
  github.com/Forvi/maxrent/internal/ports:
    interfaces:
      MessageSender:
      UserRepository:
