// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Forvi/maxrent/internal/features/user/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUserWriter is an autogenerated mock type for the UserWriter type
type MockUserWriter struct {
	mock.Mock
}

type MockUserWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserWriter) EXPECT() *MockUserWriter_Expecter {
	return &MockUserWriter_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *MockUserWriter) CreateUser(ctx context.Context, user domain.User) (domain.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserWriter_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserWriter_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockUserWriter_Expecter) CreateUser(ctx interface{}, user interface{}) *MockUserWriter_CreateUser_Call {
	return &MockUserWriter_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUserWriter_CreateUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockUserWriter_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *MockUserWriter_CreateUser_Call) Return(_a0 domain.User, _a1 error) *MockUserWriter_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserWriter_CreateUser_Call) RunAndReturn(run func(context.Context, domain.User) (domain.User, error)) *MockUserWriter_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserWriter creates a new instance of MockUserWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserWriter {
	mock := &MockUserWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
