// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	listing "github.com/Forvi/maxrent/internal/domain/listing"
	mock "github.com/stretchr/testify/mock"

	party "github.com/Forvi/maxrent/internal/domain/party"
)

// MockContractPartyRepository is an autogenerated mock type for the ContractPartyRepository type
type MockContractPartyRepository struct {
	mock.Mock
}

type MockContractPartyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContractPartyRepository) EXPECT() *MockContractPartyRepository_Expecter {
	return &MockContractPartyRepository_Expecter{mock: &_m.Mock}
}

// SaveDocumentToken provides a mock function with given fields: ctx, listingID, token
func (_m *MockContractPartyRepository) SaveDocumentToken(ctx context.Context, listingID listing.ID, token string) error {
	ret := _m.Called(ctx, listingID, token)

	if len(ret) == 0 {
		panic("no return value specified for SaveDocumentToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, listing.ID, string) error); ok {
		r0 = rf(ctx, listingID, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContractPartyRepository_SaveDocumentToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDocumentToken'
type MockContractPartyRepository_SaveDocumentToken_Call struct {
	*mock.Call
}

// SaveDocumentToken is a helper method to define mock.On call
//   - ctx context.Context
//   - listingID listing.ID
//   - token string
func (_e *MockContractPartyRepository_Expecter) SaveDocumentToken(ctx interface{}, listingID interface{}, token interface{}) *MockContractPartyRepository_SaveDocumentToken_Call {
	return &MockContractPartyRepository_SaveDocumentToken_Call{Call: _e.mock.On("SaveDocumentToken", ctx, listingID, token)}
}

func (_c *MockContractPartyRepository_SaveDocumentToken_Call) Run(run func(ctx context.Context, listingID listing.ID, token string)) *MockContractPartyRepository_SaveDocumentToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(listing.ID), args[2].(string))
	})
	return _c
}

func (_c *MockContractPartyRepository_SaveDocumentToken_Call) Return(_a0 error) *MockContractPartyRepository_SaveDocumentToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContractPartyRepository_SaveDocumentToken_Call) RunAndReturn(run func(context.Context, listing.ID, string) error) *MockContractPartyRepository_SaveDocumentToken_Call {
	_c.Call.Return(run)
	return _c
}

// SetPartyData provides a mock function with given fields: ctx, listingID, _a2, data
func (_m *MockContractPartyRepository) SetPartyData(ctx context.Context, listingID listing.ID, _a2 party.Party, data listing.ContractData) error {
	ret := _m.Called(ctx, listingID, _a2, data)

	if len(ret) == 0 {
		panic("no return value specified for SetPartyData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, listing.ID, party.Party, listing.ContractData) error); ok {
		r0 = rf(ctx, listingID, _a2, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContractPartyRepository_SetPartyData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPartyData'
type MockContractPartyRepository_SetPartyData_Call struct {
	*mock.Call
}

// SetPartyData is a helper method to define mock.On call
//   - ctx context.Context
//   - listingID listing.ID
//   - _a2 party.Party
//   - data listing.ContractData
func (_e *MockContractPartyRepository_Expecter) SetPartyData(ctx interface{}, listingID interface{}, _a2 interface{}, data interface{}) *MockContractPartyRepository_SetPartyData_Call {
	return &MockContractPartyRepository_SetPartyData_Call{Call: _e.mock.On("SetPartyData", ctx, listingID, _a2, data)}
}

func (_c *MockContractPartyRepository_SetPartyData_Call) Run(run func(ctx context.Context, listingID listing.ID, _a2 party.Party, data listing.ContractData)) *MockContractPartyRepository_SetPartyData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(listing.ID), args[2].(party.Party), args[3].(listing.ContractData))
	})
	return _c
}

func (_c *MockContractPartyRepository_SetPartyData_Call) Return(_a0 error) *MockContractPartyRepository_SetPartyData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContractPartyRepository_SetPartyData_Call) RunAndReturn(run func(context.Context, listing.ID, party.Party, listing.ContractData) error) *MockContractPartyRepository_SetPartyData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContractPartyRepository creates a new instance of MockContractPartyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContractPartyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContractPartyRepository {
	mock := &MockContractPartyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
