// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	listing "github.com/Forvi/maxrent/internal/domain/listing"
	mock "github.com/stretchr/testify/mock"

	user "github.com/Forvi/maxrent/internal/domain/user"
)

// MockListingRepository is an autogenerated mock type for the ListingRepository type
type MockListingRepository struct {
	mock.Mock
}

type MockListingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListingRepository) EXPECT() *MockListingRepository_Expecter {
	return &MockListingRepository_Expecter{mock: &_m.Mock}
}

// CodeTaken provides a mock function with given fields: ctx, code
func (_m *MockListingRepository) CodeTaken(ctx context.Context, code listing.Code) (bool, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for CodeTaken")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, listing.Code) (bool, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, listing.Code) bool); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, listing.Code) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListingRepository_CodeTaken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CodeTaken'
type MockListingRepository_CodeTaken_Call struct {
	*mock.Call
}

// CodeTaken is a helper method to define mock.On call
//   - ctx context.Context
//   - code listing.Code
func (_e *MockListingRepository_Expecter) CodeTaken(ctx interface{}, code interface{}) *MockListingRepository_CodeTaken_Call {
	return &MockListingRepository_CodeTaken_Call{Call: _e.mock.On("CodeTaken", ctx, code)}
}

func (_c *MockListingRepository_CodeTaken_Call) Run(run func(ctx context.Context, code listing.Code)) *MockListingRepository_CodeTaken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(listing.Code))
	})
	return _c
}

func (_c *MockListingRepository_CodeTaken_Call) Return(_a0 bool, _a1 error) *MockListingRepository_CodeTaken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListingRepository_CodeTaken_Call) RunAndReturn(run func(context.Context, listing.Code) (bool, error)) *MockListingRepository_CodeTaken_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, l
func (_m *MockListingRepository) Create(ctx context.Context, l listing.Listing) (listing.Listing, error) {
	ret := _m.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 listing.Listing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, listing.Listing) (listing.Listing, error)); ok {
		return rf(ctx, l)
	}
	if rf, ok := ret.Get(0).(func(context.Context, listing.Listing) listing.Listing); ok {
		r0 = rf(ctx, l)
	} else {
		r0 = ret.Get(0).(listing.Listing)
	}

	if rf, ok := ret.Get(1).(func(context.Context, listing.Listing) error); ok {
		r1 = rf(ctx, l)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockListingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - l listing.Listing
func (_e *MockListingRepository_Expecter) Create(ctx interface{}, l interface{}) *MockListingRepository_Create_Call {
	return &MockListingRepository_Create_Call{Call: _e.mock.On("Create", ctx, l)}
}

func (_c *MockListingRepository_Create_Call) Run(run func(ctx context.Context, l listing.Listing)) *MockListingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(listing.Listing))
	})
	return _c
}

func (_c *MockListingRepository_Create_Call) Return(_a0 listing.Listing, _a1 error) *MockListingRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListingRepository_Create_Call) RunAndReturn(run func(context.Context, listing.Listing) (listing.Listing, error)) *MockListingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByLandlord provides a mock function with given fields: ctx, landlordID
func (_m *MockListingRepository) FindActiveByLandlord(ctx context.Context, landlordID user.ID) (listing.Listing, error) {
	ret := _m.Called(ctx, landlordID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByLandlord")
	}

	var r0 listing.Listing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.ID) (listing.Listing, error)); ok {
		return rf(ctx, landlordID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.ID) listing.Listing); ok {
		r0 = rf(ctx, landlordID)
	} else {
		r0 = ret.Get(0).(listing.Listing)
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.ID) error); ok {
		r1 = rf(ctx, landlordID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListingRepository_FindActiveByLandlord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByLandlord'
type MockListingRepository_FindActiveByLandlord_Call struct {
	*mock.Call
}

// FindActiveByLandlord is a helper method to define mock.On call
//   - ctx context.Context
//   - landlordID user.ID
func (_e *MockListingRepository_Expecter) FindActiveByLandlord(ctx interface{}, landlordID interface{}) *MockListingRepository_FindActiveByLandlord_Call {
	return &MockListingRepository_FindActiveByLandlord_Call{Call: _e.mock.On("FindActiveByLandlord", ctx, landlordID)}
}

func (_c *MockListingRepository_FindActiveByLandlord_Call) Run(run func(ctx context.Context, landlordID user.ID)) *MockListingRepository_FindActiveByLandlord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.ID))
	})
	return _c
}

func (_c *MockListingRepository_FindActiveByLandlord_Call) Return(_a0 listing.Listing, _a1 error) *MockListingRepository_FindActiveByLandlord_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListingRepository_FindActiveByLandlord_Call) RunAndReturn(run func(context.Context, user.ID) (listing.Listing, error)) *MockListingRepository_FindActiveByLandlord_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *MockListingRepository) FindByCode(ctx context.Context, code listing.Code) (listing.Listing, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 listing.Listing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, listing.Code) (listing.Listing, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, listing.Code) listing.Listing); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(listing.Listing)
	}

	if rf, ok := ret.Get(1).(func(context.Context, listing.Code) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListingRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockListingRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code listing.Code
func (_e *MockListingRepository_Expecter) FindByCode(ctx interface{}, code interface{}) *MockListingRepository_FindByCode_Call {
	return &MockListingRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, code)}
}

func (_c *MockListingRepository_FindByCode_Call) Run(run func(ctx context.Context, code listing.Code)) *MockListingRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(listing.Code))
	})
	return _c
}

func (_c *MockListingRepository_FindByCode_Call) Return(_a0 listing.Listing, _a1 error) *MockListingRepository_FindByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListingRepository_FindByCode_Call) RunAndReturn(run func(context.Context, listing.Code) (listing.Listing, error)) *MockListingRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockListingRepository) FindByID(ctx context.Context, id listing.ID) (listing.Listing, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 listing.Listing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, listing.ID) (listing.Listing, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, listing.ID) listing.Listing); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(listing.Listing)
	}

	if rf, ok := ret.Get(1).(func(context.Context, listing.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListingRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockListingRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id listing.ID
func (_e *MockListingRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockListingRepository_FindByID_Call {
	return &MockListingRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockListingRepository_FindByID_Call) Run(run func(ctx context.Context, id listing.ID)) *MockListingRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(listing.ID))
	})
	return _c
}

func (_c *MockListingRepository_FindByID_Call) Return(_a0 listing.Listing, _a1 error) *MockListingRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListingRepository_FindByID_Call) RunAndReturn(run func(context.Context, listing.ID) (listing.Listing, error)) *MockListingRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, l
func (_m *MockListingRepository) Update(ctx context.Context, l listing.Listing) error {
	ret := _m.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, listing.Listing) error); ok {
		r0 = rf(ctx, l)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListingRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockListingRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - l listing.Listing
func (_e *MockListingRepository_Expecter) Update(ctx interface{}, l interface{}) *MockListingRepository_Update_Call {
	return &MockListingRepository_Update_Call{Call: _e.mock.On("Update", ctx, l)}
}

func (_c *MockListingRepository_Update_Call) Run(run func(ctx context.Context, l listing.Listing)) *MockListingRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(listing.Listing))
	})
	return _c
}

func (_c *MockListingRepository_Update_Call) Return(_a0 error) *MockListingRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListingRepository_Update_Call) RunAndReturn(run func(context.Context, listing.Listing) error) *MockListingRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListingRepository creates a new instance of MockListingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListingRepository {
	mock := &MockListingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
